version: '3'
services:
  yottadb:
    image: yottadb/yottadb:latest
    container_name: yottadb_container
    # environment:
    #   - ydb_dir=/data/yottadb
    #   - gtmdir=/data/yottadb
    ports:
      - "1337:1337"
    environment:
      - YOTTA_DB_PORT=1337
    volumes:
      - ./data:/data
    command: | 
      bash -c "
      source /usr/local/lib/yottadb/r1.32_x86_64/ydb_env_set &&
      ydb -run ^GDE &&
      ydb -run ^ZSY &&
      while true; do sleep 1000; done;
      "

  yottadb_init:
    depends_on:
      - yottadb_container
    image: yottadb/yottadb
    container_name: yottadb_init
    volumes:
      - yotta_data:/data/yottadb
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      source /usr/local/lib/yottadb/r1.32_x86_64/ydb_env_set &&
      ydb -run \"SET ^myglobal('test')='Hello, YottaDB!'\" &&
      echo 'Value set in YottaDB: ^myglobal(test) = Hello, YottaDB!'
      "
volumes:
  yotta_data:






