version: '3.8'

services:
  yottadb:
    image: download.yottadb.com/yottadb/yottadb-debian:latest-master
    container_name: yottadb
    volumes:
      - ./ydb-data:/data
    environment:
      - YDB_DIR=/data
    entrypoint: ["sh", "-c", "tail -f /dev/null"]

volumes:
  ydb-data: