---
- name: Install Docker, Docker Compose, YottaDB, and GCC on Ubuntu 24.04
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Print Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Install Docker Compose
      shell: |
        DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version

    - name: Print Docker Compose version
      debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"

    # Install YottaDB and GCC

    - name: Install dependencies for YottaDB and GCC
      apt:
        name:
          - file
          - binutils
          - libelf-dev
          - libicu-dev
          - nano
          - wget
          - ca-certificates
          - gcc
        state: present

    - name: Create temporary directory for YottaDB installation
      file:
        path: /tmp/tmp
        state: directory
        mode: '0755'

    - name: Download YottaDB installation script
      get_url:
        url: https://download.yottadb.com/ydbinstall.sh
        dest: /tmp/tmp/ydbinstall.sh
        mode: '0755'

    - name: Make YottaDB installation script executable
      file:
        path: /tmp/tmp/ydbinstall.sh
        mode: '0755'
        state: file

    - name: Install YottaDB
      shell: |
        cd /tmp/tmp
        sudo ./ydbinstall.sh --utf8 default --verbose
      args:
        executable: /bin/bash

    - name: Set up YottaDB environment variables
      shell: |
        source $(pkg-config --variable=prefix yottadb)/ydb_env_set
      args:
        executable: /bin/bash
      environment:
        YDB_DIR: "/usr/local/lib/yottadb"  # Change the path to match your installation if necessary

    - name: Verify YottaDB installation
      command: ydb
      register: yotta_version

    - name: Print YottaDB version
      debug:
        msg: "YottaDB version: {{ yotta_version.stdout }}"
